version: '2.1'

services:
  exporter:
    build: .
    restart: unless-stopped
    environment:
      UPTIMEROBOT_API_KEY: u123456-1a2b3c4d5e6f7890abc12323
    ports:
      - 9705:9705
    read_only: true
